# Generated by Django 5.2.4 on 2025-07-17 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotIntent',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='avg_cost_per_day',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='best_season',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name_nepali',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='region',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useritinerary',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='useritinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='travel_style',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='intent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('city', 'City'), ('mountain', 'Mountain'), ('nature', 'Nature'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('historical', 'Historical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.destination'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transport_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('flight', 'Flight'), ('jeep', 'Jeep'), ('private', 'Private Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useritinerary',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='core.destination'),
        ),
    ]
