# Generated by Django 5.2.4 on 2025-09-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_itineraryitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 9, 6)),
            preserve_default=False,
        ),
    ]
