# Generated by Django 5.1.5 on 2025-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_destination_options_destination_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='from_destination',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='to_destination',
            new_name='to_location',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='transport_type',
        ),
        migrations.AddField(
            model_name='transportation',
            name='mode',
            field=models.CharField(choices=[('bus', 'Bus'), ('flight', 'Flight'), ('jeep', 'Jeep'), ('private', 'Private Vehicle'), ('car_rental', 'Car Rental'), ('taxi', 'Taxi')], default='bus', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='duration',
            field=models.DurationField(help_text='Travel duration'),
        ),
    ]
